### ISSUE TITLE
Add Url video support and demo button + es6 import

### ISSUE THREAD

**Issue by remmel** [marek-simonik/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo#3]
Hi thanks for your application :)

Because I'ld like to use your rgbd format in my project https://www.metalograms.com/demo

I want to push 2 PRs:
-  [x] #4
   - handle url video
   - commit your goat mp4 in that repo
   - make a button to display your goat mp4 and an url (eg "https://demos.record3d.app/#demo") to easily develop and quickly show to visitors an example without the need to download and upload the mp4 to see a demo
- [x] #5 
Use es6 import (vanilly JS, without bundler/webpack) to easily use that lib
- [ ] 3. add it in npmjs.com ?

**Comment by remmel** [comment]
2. es6 import
Here is the code related with es6. OK for me, but it imports twice the three@0.147.0 as that one is included in aframe (not es6 import) and also needed in es6 import code

https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/compare/master...remmel:record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo:es6

**Comment by marek-simonik** [comment]
Hi and thanks for your contributions :)!

I've just merged your PR #4 for URL video source. I wanted to add URL video source and also a YouTube video source for some time, but I couldn't get to it yet, so I appreciate your work.

Feel free to push the second PR (es6 version). There are a few minor issues in the [es6 branch](https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/compare/master...remmel:record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo:es6) related mainly to WiFi streaming, but otherwise I also think it's OK.

List of things to fix in the es6 version:

1. [index.html](https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/compare/master...remmel:record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo:es6#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R90): import `WiFiStreamedVideoSource` 
```js
import {WiFiStreamedVideoSource} from "./js/app/video-sources/WiFiStreamedVideoSource.js";
```
2. [SignalingClient.js](https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/compare/master...remmel:record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo:es6#diff-e67a18fe894004ce7de09c45b512cbb1c90fe8b76df763becaca99416abc1264R33): `export` the `getMetadata()` function
```js
export function getMetadata(serverURL)
```
3. [WiFiStreamedVideoSource.js](https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/compare/master...remmel:record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo:es6#diff-9f76f18b59c8fdcc4c4874a936a014ee13d91121496b734fc76571bd2d67bf81R2): `import` missing pieces from `SignalingClient`
```js
import {Record3DSignalingClient, getMetadata} from "./SignalingClient.js";
```
I'm not sure if it's just me or if you noticed this too, but when I tried the es6 version, my browser kept waiting quite a long time for `unpkg.com`. I'll test with other CDNs.

**Comment by remmel** [comment]
Thanks for you feedbacks, I forgot to test the wifi feature... added it in my fork. I'll try to push that thoses days. https://github.com/remmel/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/tree/es6

About unpkg.com I also had the same feeling (probably for other libs on other project). FYI threejs is also using it https://threejs.org/docs/index.html#manual/en/introduction/Installation

**Comment by remmel** [comment]
Agree, fetching https://unpkg.com/three@0.147.0/examples/jsm/libs/lil-gui.module.min.js takes ~30s (but when you reload right after, it seems to be cached) - changing cdn or using https://www.npmjs.com/package/lil-gui could be a good idea... or waiting that something being fixed on unpkg server (it's look more of a unpkg problem)

**Comment by marek-simonik** [comment]
Thanks for including the fixes. I think the issue with delay on unpkg's servers has been fixed, `lil-gui` loads almost immediately for me now (even when downloading with `wget`), but let's keep jsdelivr for now. The es6 PR has been merged.

**Comment by remmel** [comment]
Great!
